--- #YAML:1.0
name:                Email-ConstantContact
version:             0.01
abstract:            Perl interface to the ConstantContact API
license:             perl
author:              
    - Adam Rich <arich@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42_01
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
